apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-default-cert
  labels:
    app: cert-{{ include "tyk-pro.fullname" . }}
    chart: {{ include "tyk-pro.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  tyk.local.crt: |-
    {{ .Files.Get "certs/tyk.local.crt" | b64enc }}
  tyk.local.key: |-
    {{ .Files.Get "certs/tyk.local.key" | b64enc }}
